routes/web.php
<?php


//Route::redirect('/', '/login');
Route::get('/', 'HomeController@index')->name('homesite');

Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

/* By calling Auth::routes([]), Laravel automatically generates the authentication routes,
including the registration route, with the necessary controllers and methods.
The generated routes can be found in the routes/web.php file. */

//Route contact form and contact/thankyou view

Route::get('/contact', 'ContactController@showForm')->name('contact');
Route::post('/contact', 'ContactController@submitForm')->name('contact.submit');
Route::get('/contact/thankyou', 'ContactController@thankYou')->name('contact.thankyou');

// Authentication routes with email verification
Auth::routes(['verify' => true]);



Auth::routes([]);

//All Views routes

Route::view('/about', 'about')->name('about');

//Add Statistic in the home.blade.php
Route::get('/home', 'DashboardController@index');


Route::get('/welcome', function () {
    return view('welcome');
})->name('welcome');


Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Person
    Route::delete('people/destroy', 'PersonController@massDestroy')->name('people.massDestroy');
    Route::resource('people', 'PersonController');

    // Phenological Observation
    Route::delete('phenological-observations/destroy', 'PhenologicalObservationController@massDestroy')->name('phenological-observations.massDestroy');
    Route::resource('phenological-observations', 'PhenologicalObservationController');

    // Blossoming Time
    Route::delete('blossoming-times/destroy', 'BlossomingTimeController@massDestroy')->name('blossoming-times.massDestroy');
    Route::resource('blossoming-times', 'BlossomingTimeController');

    // Plant Observed
    Route::delete('plant-observeds/destroy', 'PlantObservedController@massDestroy')->name('plant-observeds.massDestroy');
    Route::resource('plant-observeds', 'PlantObservedController');

    // Sun Exposure
    Route::delete('sun-exposures/destroy', 'SunExposureController@massDestroy')->name('sun-exposures.massDestroy');
    Route::resource('sun-exposures', 'SunExposureController');

    // Slope
    Route::delete('slopes/destroy', 'SlopeController@massDestroy')->name('slopes.massDestroy');
    Route::resource('slopes', 'SlopeController');

    // Sorroundings
    Route::delete('sorroundings/destroy', 'SorroundingsController@massDestroy')->name('sorroundings.massDestroy');
    Route::resource('sorroundings', 'SorroundingsController');

    // Plant
    Route::delete('plants/destroy', 'PlantController@massDestroy')->name('plants.massDestroy');
    Route::resource('plants', 'PlantController');

    // Observation Zone
    Route::delete('observation-zones/destroy', 'ObservationZoneController@massDestroy')->name('observation-zones.massDestroy');
    Route::resource('observation-zones', 'ObservationZoneController');

    // Location
    Route::delete('locations/destroy', 'LocationController@massDestroy')->name('locations.massDestroy');
    Route::resource('locations', 'LocationController');

    // Plant Image
    Route::delete('plant-images/destroy', 'PlantImageController@massDestroy')->name('plant-images.massDestroy');
    Route::post('plant-images/media', 'PlantImageController@storeMedia')->name('plant-images.storeMedia');
    Route::post('plant-images/ckmedia', 'PlantImageController@storeCKEditorImages')->name('plant-images.storeCKEditorImages');
    Route::resource('plant-images', 'PlantImageController');

    // Flower Image
    Route::delete('flower-images/destroy', 'FlowerImageController@massDestroy')->name('flower-images.massDestroy');
    Route::post('flower-images/media', 'FlowerImageController@storeMedia')->name('flower-images.storeMedia');
    Route::post('flower-images/ckmedia', 'FlowerImageController@storeCKEditorImages')->name('flower-images.storeCKEditorImages');
    Route::resource('flower-images', 'FlowerImageController');

    // Bloom Start Period
    Route::delete('bloom-start-periods/destroy', 'BloomStartPeriodController@massDestroy')->name('bloom-start-periods.massDestroy');
    Route::resource('bloom-start-periods', 'BloomStartPeriodController');

    // Bloom End Period
    Route::delete('bloom-end-periods/destroy', 'BloomEndPeriodController@massDestroy')->name('bloom-end-periods.massDestroy');
    Route::resource('bloom-end-periods', 'BloomEndPeriodController');


});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

app/Models/SunExposure.php
<?php

namespace App\Models;

use DateTimeInterface;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class SunExposure extends Model
{
    use SoftDeletes, HasFactory;

    public $table = 'sun_exposures';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'sun_exposure',
        'notes',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/Admin/SunExposureController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroySunExposureRequest;
use App\Http\Requests\StoreSunExposureRequest;
use App\Http\Requests\UpdateSunExposureRequest;
use App\Models\SunExposure;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class SunExposureController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('sun_exposure_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $sunExposures = SunExposure::all();

        return view('admin.sunExposures.index', compact('sunExposures'));
    }

    public function create()
    {
        abort_if(Gate::denies('sun_exposure_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.sunExposures.create');
    }

    public function store(StoreSunExposureRequest $request)
    {
        $sunExposure = SunExposure::create($request->all());

        return redirect()->route('admin.sun-exposures.index');
    }

    public function edit(SunExposure $sunExposure)
    {
        abort_if(Gate::denies('sun_exposure_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.sunExposures.edit', compact('sunExposure'));
    }

    public function update(UpdateSunExposureRequest $request, SunExposure $sunExposure)
    {
        $sunExposure->update($request->all());

        return redirect()->route('admin.sun-exposures.index');
    }

    public function show(SunExposure $sunExposure)
    {
        abort_if(Gate::denies('sun_exposure_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.sunExposures.show', compact('sunExposure'));
    }

    public function destroy(SunExposure $sunExposure)
    {
        abort_if(Gate::denies('sun_exposure_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $sunExposure->delete();

        return back();
    }

    public function massDestroy(MassDestroySunExposureRequest $request)
    {
        $sunExposures = SunExposure::find(request('ids'));

        foreach ($sunExposures as $sunExposure) {
            $sunExposure->delete();
        }

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/sunExposures/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.sunExposure.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.sun-exposures.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="sun_exposure">{{ trans('cruds.sunExposure.fields.sun_exposure') }}</label>
                <input class="form-control {{ $errors->has('sun_exposure') ? 'is-invalid' : '' }}" type="text" name="sun_exposure" id="sun_exposure" value="{{ old('sun_exposure', '') }}">
                @if($errors->has('sun_exposure'))
                    <div class="invalid-feedback">
                        {{ $errors->first('sun_exposure') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.sunExposure.fields.sun_exposure_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="notes">{{ trans('cruds.sunExposure.fields.notes') }}</label>
                <input class="form-control {{ $errors->has('notes') ? 'is-invalid' : '' }}" type="text" name="notes" id="notes" value="{{ old('notes', '') }}">
                @if($errors->has('notes'))
                    <div class="invalid-feedback">
                        {{ $errors->first('notes') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.sunExposure.fields.notes_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/sunExposures/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.sunExposure.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.sun-exposures.update", [$sunExposure->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label for="sun_exposure">{{ trans('cruds.sunExposure.fields.sun_exposure') }}</label>
                <input class="form-control {{ $errors->has('sun_exposure') ? 'is-invalid' : '' }}" type="text" name="sun_exposure" id="sun_exposure" value="{{ old('sun_exposure', $sunExposure->sun_exposure) }}">
                @if($errors->has('sun_exposure'))
                    <div class="invalid-feedback">
                        {{ $errors->first('sun_exposure') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.sunExposure.fields.sun_exposure_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="notes">{{ trans('cruds.sunExposure.fields.notes') }}</label>
                <input class="form-control {{ $errors->has('notes') ? 'is-invalid' : '' }}" type="text" name="notes" id="notes" value="{{ old('notes', $sunExposure->notes) }}">
                @if($errors->has('notes'))
                    <div class="invalid-feedback">
                        {{ $errors->first('notes') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.sunExposure.fields.notes_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/sunExposures/index.blade.php
@extends('layouts.admin')
@section('content')
@can('sun_exposure_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.sun-exposures.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.sunExposure.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.sunExposure.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-SunExposure">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.sunExposure.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.sunExposure.fields.sun_exposure') }}
                        </th>
                        <th>
                            {{ trans('cruds.sunExposure.fields.notes') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($sunExposures as $key => $sunExposure)
                        <tr data-entry-id="{{ $sunExposure->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $sunExposure->id ?? '' }}
                            </td>
                            <td>
                                {{ $sunExposure->sun_exposure ?? '' }}
                            </td>
                            <td>
                                {{ $sunExposure->notes ?? '' }}
                            </td>
                            <td>
                                @can('sun_exposure_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.sun-exposures.show', $sunExposure->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('sun_exposure_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.sun-exposures.edit', $sunExposure->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('sun_exposure_delete')
                                    <form action="{{ route('admin.sun-exposures.destroy', $sunExposure->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('sun_exposure_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.sun-exposures.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-SunExposure:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection

resources/views/admin/sunExposures/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.sunExposure.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.sun-exposures.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.sunExposure.fields.id') }}
                        </th>
                        <td>
                            {{ $sunExposure->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.sunExposure.fields.sun_exposure') }}
                        </th>
                        <td>
                            {{ $sunExposure->sun_exposure }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.sunExposure.fields.notes') }}
                        </th>
                        <td>
                            {{ $sunExposure->notes }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.sun-exposures.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection