routes/web.php
<?php


//Route::redirect('/', '/login');
Route::get('/', 'HomeController@index')->name('homesite');

Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

/* By calling Auth::routes([]), Laravel automatically generates the authentication routes,
including the registration route, with the necessary controllers and methods.
The generated routes can be found in the routes/web.php file. */

//Route contact form and contact/thankyou view

Route::get('/contact', 'ContactController@showForm')->name('contact');
Route::post('/contact', 'ContactController@submitForm')->name('contact.submit');
Route::get('/contact/thankyou', 'ContactController@thankYou')->name('contact.thankyou');

// Authentication routes with email verification
Auth::routes(['verify' => true]);



Auth::routes([]);

//All Views routes

Route::view('/about', 'about')->name('about');

//Add Statistic in the home.blade.php
Route::get('/home', 'DashboardController@index');


Route::get('/welcome', function () {
    return view('welcome');
})->name('welcome');


Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Person
    Route::delete('people/destroy', 'PersonController@massDestroy')->name('people.massDestroy');
    Route::resource('people', 'PersonController');

    // Phenological Observation
    Route::delete('phenological-observations/destroy', 'PhenologicalObservationController@massDestroy')->name('phenological-observations.massDestroy');
    Route::resource('phenological-observations', 'PhenologicalObservationController');

    // Blossoming Time
    Route::delete('blossoming-times/destroy', 'BlossomingTimeController@massDestroy')->name('blossoming-times.massDestroy');
    Route::resource('blossoming-times', 'BlossomingTimeController');

    // Plant Observed
    Route::delete('plant-observeds/destroy', 'PlantObservedController@massDestroy')->name('plant-observeds.massDestroy');
    Route::resource('plant-observeds', 'PlantObservedController');

    // Sun Exposure
    Route::delete('sun-exposures/destroy', 'SunExposureController@massDestroy')->name('sun-exposures.massDestroy');
    Route::resource('sun-exposures', 'SunExposureController');

    // Slope
    Route::delete('slopes/destroy', 'SlopeController@massDestroy')->name('slopes.massDestroy');
    Route::resource('slopes', 'SlopeController');

    // Sorroundings
    Route::delete('sorroundings/destroy', 'SorroundingsController@massDestroy')->name('sorroundings.massDestroy');
    Route::resource('sorroundings', 'SorroundingsController');

    // Plant
    Route::delete('plants/destroy', 'PlantController@massDestroy')->name('plants.massDestroy');
    Route::resource('plants', 'PlantController');

    // Observation Zone
    Route::delete('observation-zones/destroy', 'ObservationZoneController@massDestroy')->name('observation-zones.massDestroy');
    Route::resource('observation-zones', 'ObservationZoneController');

    // Location
    Route::delete('locations/destroy', 'LocationController@massDestroy')->name('locations.massDestroy');
    Route::resource('locations', 'LocationController');

    // Plant Image
    Route::delete('plant-images/destroy', 'PlantImageController@massDestroy')->name('plant-images.massDestroy');
    Route::post('plant-images/media', 'PlantImageController@storeMedia')->name('plant-images.storeMedia');
    Route::post('plant-images/ckmedia', 'PlantImageController@storeCKEditorImages')->name('plant-images.storeCKEditorImages');
    Route::resource('plant-images', 'PlantImageController');

    // Flower Image
    Route::delete('flower-images/destroy', 'FlowerImageController@massDestroy')->name('flower-images.massDestroy');
    Route::post('flower-images/media', 'FlowerImageController@storeMedia')->name('flower-images.storeMedia');
    Route::post('flower-images/ckmedia', 'FlowerImageController@storeCKEditorImages')->name('flower-images.storeCKEditorImages');
    Route::resource('flower-images', 'FlowerImageController');

    // Bloom Start Period
    Route::delete('bloom-start-periods/destroy', 'BloomStartPeriodController@massDestroy')->name('bloom-start-periods.massDestroy');
    Route::resource('bloom-start-periods', 'BloomStartPeriodController');

    // Bloom End Period
    Route::delete('bloom-end-periods/destroy', 'BloomEndPeriodController@massDestroy')->name('bloom-end-periods.massDestroy');
    Route::resource('bloom-end-periods', 'BloomEndPeriodController');


});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

app/Models/FlowerImage.php
<?php

namespace App\Models;

use DateTimeInterface;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

class FlowerImage extends Model implements HasMedia
{
    use SoftDeletes, InteractsWithMedia, HasFactory;

    public $table = 'flower_images';

    protected $appends = [
        'flower_pic',
    ];

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }

    public function registerMediaConversions(Media $media = null): void
    {
        $this->addMediaConversion('thumb')->fit('crop', 50, 50);
        $this->addMediaConversion('preview')->fit('crop', 120, 120);
    }

    public function getFlowerPicAttribute()
    {
        $file = $this->getMedia('flower_pic')->last();
        if ($file) {
            $file->url       = $file->getUrl();
            $file->thumbnail = $file->getUrl('thumb');
            $file->preview   = $file->getUrl('preview');
        }

        return $file;
    }
}

app/Http/Controllers/Admin/FlowerImageController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\MediaUploadingTrait;
use App\Http\Requests\MassDestroyFlowerImageRequest;
use App\Http\Requests\StoreFlowerImageRequest;
use App\Http\Requests\UpdateFlowerImageRequest;
use App\Models\FlowerImage;
use Gate;
use Illuminate\Http\Request;
use Spatie\MediaLibrary\MediaCollections\Models\Media;
use Symfony\Component\HttpFoundation\Response;

class FlowerImageController extends Controller
{
    use MediaUploadingTrait;

    public function index()
    {
        abort_if(Gate::denies('flower_image_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $flowerImages = FlowerImage::with(['media'])->get();

        return view('admin.flowerImages.index', compact('flowerImages'));
    }

    public function create()
    {
        abort_if(Gate::denies('flower_image_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.flowerImages.create');
    }

    public function store(StoreFlowerImageRequest $request)
    {
        $flowerImage = FlowerImage::create($request->all());

        if ($request->input('flower_pic', false)) {
            $flowerImage->addMedia(storage_path('tmp/uploads/' . basename($request->input('flower_pic'))))->toMediaCollection('flower_pic');
        }

        if ($media = $request->input('ck-media', false)) {
            Media::whereIn('id', $media)->update(['model_id' => $flowerImage->id]);
        }

        return redirect()->route('admin.flower-images.index');
    }

    public function edit(FlowerImage $flowerImage)
    {
        abort_if(Gate::denies('flower_image_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.flowerImages.edit', compact('flowerImage'));
    }

    public function update(UpdateFlowerImageRequest $request, FlowerImage $flowerImage)
    {
        $flowerImage->update($request->all());

        if ($request->input('flower_pic', false)) {
            if (! $flowerImage->flower_pic || $request->input('flower_pic') !== $flowerImage->flower_pic->file_name) {
                if ($flowerImage->flower_pic) {
                    $flowerImage->flower_pic->delete();
                }
                $flowerImage->addMedia(storage_path('tmp/uploads/' . basename($request->input('flower_pic'))))->toMediaCollection('flower_pic');
            }
        } elseif ($flowerImage->flower_pic) {
            $flowerImage->flower_pic->delete();
        }

        return redirect()->route('admin.flower-images.index');
    }

    public function show(FlowerImage $flowerImage)
    {
        abort_if(Gate::denies('flower_image_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.flowerImages.show', compact('flowerImage'));
    }

    public function destroy(FlowerImage $flowerImage)
    {
        abort_if(Gate::denies('flower_image_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $flowerImage->delete();

        return back();
    }

    public function massDestroy(MassDestroyFlowerImageRequest $request)
    {
        $flowerImages = FlowerImage::find(request('ids'));

        foreach ($flowerImages as $flowerImage) {
            $flowerImage->delete();
        }

        return response(null, Response::HTTP_NO_CONTENT);
    }

    public function storeCKEditorImages(Request $request)
    {
        abort_if(Gate::denies('flower_image_create') && Gate::denies('flower_image_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $model         = new FlowerImage();
        $model->id     = $request->input('crud_id', 0);
        $model->exists = true;
        $media         = $model->addMediaFromRequest('upload')->toMediaCollection('ck-media');

        return response()->json(['id' => $media->id, 'url' => $media->getUrl()], Response::HTTP_CREATED);
    }
}

resources/views/admin/flowerImages/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.flowerImage.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.flower-images.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="flower_pic">{{ trans('cruds.flowerImage.fields.flower_pic') }}</label>
                <div class="needsclick dropzone {{ $errors->has('flower_pic') ? 'is-invalid' : '' }}" id="flower_pic-dropzone">
                </div>
                @if($errors->has('flower_pic'))
                    <div class="invalid-feedback">
                        {{ $errors->first('flower_pic') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.flowerImage.fields.flower_pic_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

@section('scripts')
<script>
    Dropzone.options.flowerPicDropzone = {
    url: '{{ route('admin.flower-images.storeMedia') }}',
    maxFilesize: 4, // MB
    acceptedFiles: '.jpeg,.jpg,.png,.gif',
    maxFiles: 1,
    addRemoveLinks: true,
    headers: {
      'X-CSRF-TOKEN': "{{ csrf_token() }}"
    },
    params: {
      size: 4,
      width: 4096,
      height: 4096
    },
    success: function (file, response) {
      $('form').find('input[name="flower_pic"]').remove()
      $('form').append('<input type="hidden" name="flower_pic" value="' + response.name + '">')
    },
    removedfile: function (file) {
      file.previewElement.remove()
      if (file.status !== 'error') {
        $('form').find('input[name="flower_pic"]').remove()
        this.options.maxFiles = this.options.maxFiles + 1
      }
    },
    init: function () {
@if(isset($flowerImage) && $flowerImage->flower_pic)
      var file = {!! json_encode($flowerImage->flower_pic) !!}
          this.options.addedfile.call(this, file)
      this.options.thumbnail.call(this, file, file.preview ?? file.preview_url)
      file.previewElement.classList.add('dz-complete')
      $('form').append('<input type="hidden" name="flower_pic" value="' + file.file_name + '">')
      this.options.maxFiles = this.options.maxFiles - 1
@endif
    },
    error: function (file, response) {
        if ($.type(response) === 'string') {
            var message = response //dropzone sends it's own error messages in string
        } else {
            var message = response.errors.file
        }
        file.previewElement.classList.add('dz-error')
        _ref = file.previewElement.querySelectorAll('[data-dz-errormessage]')
        _results = []
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            node = _ref[_i]
            _results.push(node.textContent = message)
        }

        return _results
    }
}

</script>
@endsection

resources/views/admin/flowerImages/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.flowerImage.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.flower-images.update", [$flowerImage->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label for="flower_pic">{{ trans('cruds.flowerImage.fields.flower_pic') }}</label>
                <div class="needsclick dropzone {{ $errors->has('flower_pic') ? 'is-invalid' : '' }}" id="flower_pic-dropzone">
                </div>
                @if($errors->has('flower_pic'))
                    <div class="invalid-feedback">
                        {{ $errors->first('flower_pic') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.flowerImage.fields.flower_pic_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

@section('scripts')
<script>
    Dropzone.options.flowerPicDropzone = {
    url: '{{ route('admin.flower-images.storeMedia') }}',
    maxFilesize: 4, // MB
    acceptedFiles: '.jpeg,.jpg,.png,.gif',
    maxFiles: 1,
    addRemoveLinks: true,
    headers: {
      'X-CSRF-TOKEN': "{{ csrf_token() }}"
    },
    params: {
      size: 4,
      width: 4096,
      height: 4096
    },
    success: function (file, response) {
      $('form').find('input[name="flower_pic"]').remove()
      $('form').append('<input type="hidden" name="flower_pic" value="' + response.name + '">')
    },
    removedfile: function (file) {
      file.previewElement.remove()
      if (file.status !== 'error') {
        $('form').find('input[name="flower_pic"]').remove()
        this.options.maxFiles = this.options.maxFiles + 1
      }
    },
    init: function () {
@if(isset($flowerImage) && $flowerImage->flower_pic)
      var file = {!! json_encode($flowerImage->flower_pic) !!}
          this.options.addedfile.call(this, file)
      this.options.thumbnail.call(this, file, file.preview ?? file.preview_url)
      file.previewElement.classList.add('dz-complete')
      $('form').append('<input type="hidden" name="flower_pic" value="' + file.file_name + '">')
      this.options.maxFiles = this.options.maxFiles - 1
@endif
    },
    error: function (file, response) {
        if ($.type(response) === 'string') {
            var message = response //dropzone sends it's own error messages in string
        } else {
            var message = response.errors.file
        }
        file.previewElement.classList.add('dz-error')
        _ref = file.previewElement.querySelectorAll('[data-dz-errormessage]')
        _results = []
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            node = _ref[_i]
            _results.push(node.textContent = message)
        }

        return _results
    }
}

</script>
@endsection

resources/views/admin/flowerImages/index.blade.php
@extends('layouts.admin')
@section('content')
@can('flower_image_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.flower-images.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.flowerImage.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.flowerImage.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-FlowerImage">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.flowerImage.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.flowerImage.fields.flower_pic') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($flowerImages as $key => $flowerImage)
                        <tr data-entry-id="{{ $flowerImage->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $flowerImage->id ?? '' }}
                            </td>
                            <td>
                                @if($flowerImage->flower_pic)
                                    <a href="{{ $flowerImage->flower_pic->getUrl() }}" target="_blank" style="display: inline-block">
                                        <img src="{{ $flowerImage->flower_pic->getUrl('thumb') }}">
                                    </a>
                                @endif
                            </td>
                            <td>
                                @can('flower_image_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.flower-images.show', $flowerImage->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('flower_image_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.flower-images.edit', $flowerImage->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('flower_image_delete')
                                    <form action="{{ route('admin.flower-images.destroy', $flowerImage->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('flower_image_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.flower-images.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-FlowerImage:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection

resources/views/admin/flowerImages/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.flowerImage.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.flower-images.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.flowerImage.fields.id') }}
                        </th>
                        <td>
                            {{ $flowerImage->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.flowerImage.fields.flower_pic') }}
                        </th>
                        <td>
                            @if($flowerImage->flower_pic)
                                <a href="{{ $flowerImage->flower_pic->getUrl() }}" target="_blank" style="display: inline-block">
                                    <img src="{{ $flowerImage->flower_pic->getUrl('thumb') }}">
                                </a>
                            @endif
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.flower-images.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection